### ISSUE TITLE
Question: Long load times for data

### ISSUE THREAD

**Issue by dkullmann** [citrusbyte/Healthy-Baby#16]
@lucholaf it takes a long time to load data. Do you know why? @bradybd said the m2x APIs should respond quickly

**Comment by lucholaf** [comment]
@dkullmann @bradybd I added a delay on purpose when data is created because the m2x api is async, so there's no guarantee I'll get the data on the chart once the creation process is completed on the device. I just reduced that delay as well as cache the device data on first fetch, so now it loads quite faster although there is a risk of asking for data when it's still not ready on the server. Tell me from your side if it works better for you now.

**Comment by dkullmann** [comment]
@lucholaf I'd rather have the entire screen display right away, and the graph show a loading indicator.

Then, if the graph loads successfully it displays data, otherwise it says theirs an error.

**Comment by dkullmann** [comment]
Looks better! Questions:

1. Can we show the labels (Samples, Starting BMI, Goal, etc) before the data loads in?
2. For all variables values (start, end, the values in the table, etc) can we show a dash (—) where they will appear?
3. Can the "Loading Device" element appear in the center of the graph area?
4. When the numbers are displayed can they fade in (a dissolve effect?) Quickly fade out dashes and fade in numbers - if possible match the timing of how long it takes to draw the graph line. So if the graph line takes .5 seconds then do .25 seconds for the dashes to fade out and .25 seconds for the numbers to fade in

![image](https://cloud.githubusercontent.com/assets/422899/5648473/d51c47d4-965c-11e4-9c53-5d557ab298b1.png)

**Comment by lucholaf** [comment]
@dkullmann try now, looks much better

**Comment by dkullmann** [comment]
@lucholaf awesome!

Can the labels/values that *don't change* stay instead of fading out and fading back in with the same value?

Like these:
![image](https://cloud.githubusercontent.com/assets/422899/5652256/9df37aaa-967c-11e4-9ca7-0c5a577d5e44.png)

**Comment by lucholaf** [comment]
@dkullmann pushed

**Comment by dkullmann** [comment]
@lucholaf looks great!

**Comment by dkullmann** [comment]
@lucholaf A few more items on this view:

1. I noticed that on the "kicks" screen we see "this week" repeated
2. On "baby weight" the label is cutoff by the right side of the screen
3. The table at the bottom is tappable - can we disable that? (see below)
4. Can we also disable scrolling on that table?

"this week" repeated:
![image](https://cloud.githubusercontent.com/assets/422899/5665243/064c67bc-9725-11e4-9dd2-3dfe0b8cd28a.png)

label cutoff:
![image](https://cloud.githubusercontent.com/assets/422899/5665258/24871a74-9725-11e4-9c59-df8e7c616ef7.png)

tappable table:
![image](https://cloud.githubusercontent.com/assets/422899/5665277/4973281e-9725-11e4-8446-c9865ff81b80.png)

**Comment by lucholaf** [comment]
@dkullmann completed, check it out

**Comment by dkullmann** [comment]
@lucholaf 

1. [x] Table tapping and scrolling
2. [x] Improved Labels
3. [ ] Labels are spaced awkwardly or cutoff, the image below shows the label of the "kick" graph is all the way to the right

![image](https://cloud.githubusercontent.com/assets/422899/5685379/b83553fc-9807-11e4-9c72-b041267acbd1.png)

**Comment by dkullmann** [comment]
I this issue has morphed into UI feedback and we should close it and make a new one. Thoughts?
