### ISSUE TITLE
UI: Label Spacing

### ISSUE THREAD

**Issue by dkullmann** [citrusbyte/Healthy-Baby#18]
The labels on the graph at the bottom aren't spaced properly. There should always be some space between the label and the side of the screen:

![image](https://cloud.githubusercontent.com/assets/422899/5685379/b83553fc-9807-11e4-9c72-b041267acbd1.png)

Refs #16

**Comment by dkullmann** [comment]
Here is the full screen:

![image](https://cloud.githubusercontent.com/assets/422899/5685502/c1e5285e-9808-11e4-81e1-312f0150f40e.png)

**Comment by lucholaf** [comment]
@dkullmann I added a new and bigger margin both on left and right side that is obeyed on all cases

**Comment by dkullmann** [comment]
:tada: gracias!
