### ISSUE TITLE
Fix Name - Remove "M2X" and Use "Citrusbyte" (No capital B)

### ISSUE THREAD

**Issue by dkullmann** [citrusbyte/Healthy-Baby#19]
@lucholaf 

Can you correct:
* Remove the "M2X" part of the apps name, only "Healthy Baby"
* Change "CitrusByte" to "Citrusbyte"

![img_8112](https://cloud.githubusercontent.com/assets/422899/5686756/ecde136c-9813-11e4-9f05-ff9d65acb966.PNG)

**Comment by lucholaf** [comment]
@dkullmann to remove M2X I'll need to create a new app (which involves many things as re-creating certificates, sending for app review and wait 4-5 days, etc). Then for the CitrusByte name, it's the name that was entered on the dev program, mike.joyce@citrusbyte.com appears as the agent he may have access to change that, but not sure if Apple lets you do that.

**Comment by lucholaf** [comment]
waiting for Apple review ... 
![screen shot 2015-01-12 at 10 43 35](https://cloud.githubusercontent.com/assets/106112/5703633/ec193fb6-9a47-11e4-8922-a14accc18c2b.png)

**Comment by dkullmann** [comment]
+1 thank you Luis

David Kullmann
Citrusbyte, LLC
Partner & Product Manager
408-673-0629

**Comment by lucholaf** [comment]
@dkullmann done on latest build, also asked Mike to see if he can change the company name on itunes connect.

**Comment by dkullmann** [comment]
@lucholaf where can I see it? only testflight?

**Comment by lucholaf** [comment]
@dkullmann yes testflight
