### ISSUE TITLE
Bug: Can't press "< Back" when device is loading

### ISSUE THREAD

**Issue by lucholaf** [citrusbyte/Healthy-Baby#2]
_From @dkullmann on December 26, 2014 22:59_

When the device is loading I am unable to press the back button.

![image](https://cloud.githubusercontent.com/assets/422899/5559777/e68a75b4-8d28-11e4-865b-a3313177ef2e.png)

Please allow pressing the back button even if the device hasn't completed loading yet

_Copied from original issue: citrusbyte/att-m2x-ios-demo#7_

**Comment by dkullmann** [comment]
confirmed resolved
